/**
 * Mirrors cetech-backend `src/core/constants/sports.js` (TrainingSport / sport enum values).
 */
export const SPORTS = {
  GOLF: "GOLF",
  SKATING: "SKATING",
  ICE_SKATING: "ICE_SKATING",
  TENNIS: "TENNIS",
  CRICKET: "CRICKET",
  FOOTBALL: "FOOTBALL",
  HOCKEY: "HOCKEY",
  SWIMMING: "SWIMMING",
  BOXING: "BOXING",
  WRESTLING: "WRESTLING",
  JUDO: "JUDO",
  ATHLETICS: "ATHLETICS",
  CYCLING: "CYCLING",
  BADMINTON: "BADMINTON",
  SQUASH: "SQUASH",
  RACQUETBALL: "RACQUETBALL",
  PADEL: "PADEL",
  ARCHERY: "ARCHERY",
  GYMNASTICS: "GYMNASTICS",
  BASKETBALL: "BASKETBALL",
  VOLLEYBALL: "VOLLEYBALL",
  CANOE: "CANOE",
  DIVING: "DIVING",
  EQUESTRIAN: "EQUESTRIAN",
  FENCING: "FENCING",
  HANDBALL: "HANDBALL",
  KARATE: "KARATE",
  LACROSSE: "LACROSSE",
  ROWING: "ROWING",
  SAILING: "SAILING",
  SHOOTING: "SHOOTING",
  SKATEBOARDING: "SKATEBOARDING",
  SURFING: "SURFING",
  TABLE_TENNIS: "TABLE_TENNIS",
  TAEKWONDO: "TAEKWONDO",
  TRIATHLON: "TRIATHLON",
  WATER_POLO: "WATER_POLO",
  WEIGHTLIFTING: "WEIGHTLIFTING",
};

/** Stable list of sport enum values for selects (sorted for UX). */
export const SPORT_VALUES = Object.values(SPORTS).sort((a, b) =>
  a.localeCompare(b),
);
